package com.ktprj.service

import com.ktprj.adapters.InstructorAdapters
import com.ktprj.dto.InstructorDto
import com.ktprj.entities.Instructor
import com.ktprj.repository.InstructorRepository
import org.springframework.stereotype.Service
import org.springframework.validation.annotation.Validated
import java.util.*
import javax.validation.Valid

@Service
@Validated
class InstructorService(val instructorRepository: InstructorRepository, val instructorAdapters: InstructorAdapters) {

    fun newCourse(@Valid instructor: InstructorDto): InstructorDto {
        return when (instructor.id != null) {
            true -> {
                throw  Exception("Id is autogenerated, it is not a required field")
            }
            else -> {
                val newInstructor = instructorAdapters.dtoToEntity(instructor)

                return instructorAdapters.entityToDto(instructorRepository.save(newInstructor))
            }
        }

    }

    fun findInstructorById(id: Int): Optional<Instructor> {
        return instructorRepository.findById(id)
    }

}